version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=llama3
    restart: unless-stopped

  app:
    build:
      context: .
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_URL=http://ollama:11434

volumes:
  ollama_data:
