version: '3.8'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: [ "/bin/bash", "-c", "\
          ollama serve & \
          sleep 5 && \
          ollama pull mistral && wait" ]

  app1:
    build:
      context: .
      dockerfile: Dockerfile-App1
    depends_on:
      - ollama
  app2:
    build:
      context: .
      dockerfile: Dockerfile-App2
    depends_on:
      - ollama

volumes:
  ollama_data:
