spring:
  application:
    name: aijobmatcher
  datasource:
    url: jdbc:postgresql://localhost:5432/aijobmatcher
    username: admin
    password: secret123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  chromeDriverPath: "C:\\Users\\USER\\Downloads\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe"
  offlineMode: false
  aiModels:
    - llama3.1:8b
    - mistral:7b
    - qwen3:8b
    - phi4-mini:3.8b
    - gemma3:4b
  aiEndpoint: "http://localhost:11434/v1/completions"
  jobConfigs:
    - initUrl: "https://hk.jobsdb.com/Java-jobs-in-information-communication-technology?sortmode=ListedDate"
      maxPages: 1
      rematch: false
      aiRoleplay: |
        You are a senior technical recruiter with a sharp eye for real-world fit. You evaluate candidates with strict adherence to job requirements, but you also recognize transferable skills, equivalent experience, and potential. You are blunt, honest, and never sugarcoat—but you do not auto-reject capable candidates for lacking optional or niche skills. Your assessments are grounded, balanced, and ruthless only when necessary.
      aiTask: |
        Your output must include the following sections, and they must be logically consistent:
        1. Suitability Score: A number from 0 to 10 based *strictly* on how well the candidate matches the job requirements. No inflation.
        2. Matching Strengths: List exact skills, tools, and experiences that match the job requirements.
        3. Gaps and Mismatches: List all missing, unclear, outdated, or irrelevant experience.
        4. Verdict: Provide a blunt and honest assessment based on the above, written as a clear and direct paragraph (at least 3-4 sentences). Explain exactly why the candidate is or is not suitable, referencing both matching strengths and major gaps. If the candidate lacks core skills, clearly state this and explain the likely impact on job performance.
        5. Shortlist Flag: YES only if (Suitability Score >= 6 AND no major missing skills). Otherwise print "Shortlist Flag: NO".

      candidateProfile: |
        Wai Man Lam (Ray)
        Location: Hong Kong | Availability: Immediate | Languages: Cantonese (Native), English (Fluent), Mandarin (Conversational)
        Education: BSc Computer Science, Hong Kong Baptist University (2010); Python-based final year project
        Professional Summary: Experienced Java backend developer with over 10 years of building scalable, API-driven applications using Spring Boot and modern frameworks. Skilled in REST API development, CI/CD pipelines, and cloud-ready deployments with Docker. Proficient in collaborating with offshore teams and delivering Agile projects. Actively learning AWS, microservices, and LLMs to drive innovation in job-matching platforms.
        Key Experience: Independent Projects (Mar 2025 - Present): Built a Spring Boot-based job-matching platform using Ollama LLM for candidate-job fit analysis, integrating PostgreSQL, REST APIs, and Selenium for automated web scraping. Deployed via Docker with GitHub Actions CI/CD, achieving 95% uptime in demo (viewable on personal website). Self-learning ReactJS and microservices.
        TransUnion Hong Kong (Dec 2022 - Jun 2024): Developed REST APIs for web and mobile apps using Java Spring MVC and Oracle, enabling 30% faster customer onboarding via eKYC integration and dark web monitoring. Enhanced web portal UX with JavaScript, HTML, and CSS, improving user engagement by 15%. Streamlined CI/CD with Jenkins and Maven in Agile sprints, collaborating with offshore developers (India).
        Currencyfair Asia (Jan 2022 - Oct 2022): Integrated payment gateway APIs using Spring Boot Webflux and MySQL, implementing JWT-based authentication for enhanced security. Applied TDD/BDD with Cucumber, deploying via Docker. Collaborated with offshore teams (Australia) in Agile workflows. Departed due to company restructuring.
        Hong Kong Telecom (Feb 2017 - Oct 2021): Modernized legacy telco systems with Java and Spring Framework, integrating PCCWS batch job outputs to support a major data migration. Developed REST APIs and enhanced internal portals with JavaScript and jQuery, improving usability by 25%. Guided offshore developers (China) in Waterfall SDLC.
        Arcotect Ltd & CSL (Jul 2010 - Oct 2014): Built J2EE/JavaEE (jsp/servlet) based PDF billing system on IBM WebSphere, improving customer access to billing data. Developed APIs for internal systems (struts, jQuery), enhancing data accessibility for business teams.
        Sabbaticals (Jul 2024 - Feb 2025, Nov 2014 - Sep 2015): Focused on family care while pursuing self-learning in modern tech stacks.
        Skills: Proficient: Java, Spring Boot, REST API development, PostgreSQL, MySQL, Oracle, Docker, Jenkins, Git, HTML.
        Intermediate: Spring Webflux, PL/SQL, Cucumber, JavaScript, CSS.
        Learning: AWS, ReactJS, microservices, LLMs (Ollama, ChatGPT).
        Additional: Experienced in Agile and Waterfall SDLC, offshore collaboration, and Linux/Windows operations. Familiar with COBOL, C, J2EE, Visual Basic, OpenVMS.
    - initUrl: "https://hk.jobsdb.com/jobs/part-time?sortmode=ListedDate"
      maxPages: 1
      rematch: false
      aiRoleplay: |
        You are a practical HR recruiter specializing in part-time and temporary roles. 
        You evaluate candidates realistically, focusing on schedule fit, physical demands, and transferable soft skills. 
        You are blunt and pragmatic: if the candidate cannot handle the hours or requirements, state it clearly. 
        You also consider personal interests (such as cooking) if relevant to the role.

      aiTask: |
        Your output must include the following sections:
        1. Suitability Score: A number from 0 to 10, based strictly on how well the candidate matches the job requirements.
        2. Matching Strengths: List specific traits, skills, or interests that match the role (e.g., cooking, customer service).
        3. Gaps and Mismatches: List limitations such as stamina, schedule availability, or missing required skills.
        4. Verdict: A short but blunt assessment explaining whether the candidate is a realistic fit, referencing both strengths and gaps.
        5. Shortlist Flag: YES only if (Suitability Score >= 6 AND no major disqualifying gaps). Otherwise print "Shortlist Flag: NO".

      candidateProfile: |
        Wai Man Lam (Ray)
        Location: Hong Kong | Availability: Immediate | Languages: Cantonese (Native), English (Fluent), Mandarin (Conversational)
        Professional Summary: Looking for part-time or temporary work, preferably not 5 days per week. 
        Open to flexible roles that allow practical contribution without heavy physical demands. 
        Reliable, punctual, and detail-oriented. Enjoys cooking and learning new tasks. 
        Has strong computer skills, but not seeking full-time IT positions at this time.
        Key Experience: Has worked extensively in software development but is now transitioning to part-time roles. 
        Past jobs required collaboration, attention to detail, and following structured workflows—all transferable to customer-facing or task-based roles.
        Strength & Stamina: Candidate seldom exercises and has weak strength/stamina, so physically demanding or heavy-lifting roles are unsuitable.
        Interests: Enjoys cooking, experimenting with recipes, and kitchen work. Interested in food-related part-time opportunities especially Sushi.
        Skills: 
          - Customer-facing experience from project collaborations
          - Strong attention to detail
          - Reliable with time management
          - Comfortable with technology for POS or scheduling systems
          - Cooking and kitchen tasks (personal interest, not professional training)

  

  
  
